"""add blacklists table

Revision ID: 2a81c8179d93
Revises: 66fa2d8eb34b
Create Date: 2025-09-27 13:25:37.135685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a81c8179d93'
down_revision: Union[str, Sequence[str], None] = '66fa2d8eb34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklists',
    sa.Column('token', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklists')
    # ### end Alembic commands ###
