"""change Blacklists.token from uuid to varchar

Revision ID: 5174ccffea52
Revises: 51a10719017b
Create Date: 2025-10-05 08:47:43.343185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5174ccffea52'
down_revision: Union[str, Sequence[str], None] = '51a10719017b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklists', 'token',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklists', 'token',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
