"""rename bookings.role to bookings.status

Revision ID: 51a10719017b
Revises: 96676ec0fa07
Create Date: 2025-10-01 13:22:48.866957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51a10719017b'
down_revision: Union[str, Sequence[str], None] = '96676ec0fa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='status_enum'), nullable=False))
    op.drop_column('bookings', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('role', postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='status_enum'), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'status')
    # ### end Alembic commands ###
