"""add unique constraint to  blacklists.token

Revision ID: 96676ec0fa07
Revises: 2a81c8179d93
Create Date: 2025-09-27 13:54:30.383786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96676ec0fa07'
down_revision: Union[str, Sequence[str], None] = '2a81c8179d93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'blacklists', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blacklists', type_='unique')
    # ### end Alembic commands ###
